### ISSUE TITLE
Compléter la page amendement

### ISSUE THREAD

**Issue by alexfauquette** [louis-sanna-eki/nosdeputes-front#26]
## Todo

- [ ] Relier les filtre avec les search parameters de l'url
- [ ] Ajouter une pagination des amendements
- [ ] Si un amendement n'est pas étendu, réduire la hauteur au maximum
- [ ] Ajouter filtre "status"
- [ ] Ajouter filtre député
- [ ] Utiliser les chips pour le status de l'amendement

## Needs some hints

- Récupérer le partis d'un député
- Récupérer la photo d'un député
- Récupérer la commission où l'amendement est traité
